### ISSUE TITLE
Cowboy image optimization

### ISSUE THREAD

**Issue by TrentWalton** [raygunray/reaganray.com#1]
@raygunray you might go for a tight crop on the cowboys graphic. I noticed a significant difference in file size when I removed the space to the right. Hopefully, we’ll still be able to make the background size/positioning work well, but I wanted to bring it up before you tweak.

Some image alpha’d graphics I was playing with to compare…

![cowboys](https://cloud.githubusercontent.com/assets/271248/10773905/1f98e154-7ccc-11e5-9bc2-f8f9409fcb2d.png)
![cropped-cowboys](https://cloud.githubusercontent.com/assets/271248/10773909/21f090aa-7ccc-11e5-958b-331d6e8b9720.png)

**Comment by TrentWalton** [comment]
One more thing, I fixed the image path (away from codepen) for the cowboys. I also added that alpha graphic I exported today as an option for you (the white is transparent in this one so it looks sorta multiplied). Feel free to ignore it, but I tested it and could see either option working.

**Comment by raygunray** [comment]
Ah - I think I misunderstood you when you were talking about this. Didn't realize that you were taking out the white behind the cowboys. I'd like to keep the white.

But, I was able to crunch my background image all the way down to 157 K from ~300k. So an improvement.

**Comment by raygunray** [comment]
close
