### ISSUE TITLE
Redirect blog.

### ISSUE THREAD

**Issue by TrentWalton** [raygunray/reaganray.com#11]

**Comment by TrentWalton** [comment]
@raygunray, I’ll let you close this when you can confirm the proper redirect.

http://blog.reaganray.com/post/129297690013/from-codepen-to-deployment-thesignsofaustincom
should go to
http://reaganray.com/2015/09/17/from-codepen-to-deployment-thesignsofaustincom.html

Logging my .htaccess for good measure

```
Options +FollowSymLinks
RewriteEngine On
RewriteRule ^info*$ /info.html [R=301,L]

RewriteEngine on
RewriteCond %{HTTP_HOST} ^blog.reaganray.com$
RewriteRule ^(.*)$ http://reaganray.com/$1 [R=301,L]
```

**Comment by raygunray** [comment]
Everything working now :+1:
