### ISSUE TITLE
Site header on phones

### ISSUE THREAD

**Issue by TrentWalton** [raygunray/reaganray.com#8]
<img width="360" alt="screen shot 2015-11-30 at 11 51 41 am" src="https://cloud.githubusercontent.com/assets/271248/11479661/c6436abe-9758-11e5-8de2-275deef1ea3d.png">

I bet we could do a variety of things…
* Smaller font-size
* let it go 2 lines, but add better spacing (maybe center it)

**Comment by raygunray** [comment]
Good catch - I meant to mention that. Let's just let it go 2 lines + add better spacing.

**Comment by raygunray** [comment]
Ok, calling in help on this one. Been messing with it today, but not having much luck.

**Comment by TrentWalton** [comment]
No problem! Take a look at layout.scss—I added a few media queries and some spacing below `nav` as well as a border. You may or may not like that on the sub and/or the home page, just LMK if you need help wrapping this bit up.

96f448b05a80ee7f5bca2e7934fcb9be32d2adb3

**Comment by raygunray** [comment]
Perfect - thx! I nudged things a tiny bit (made the h1 a tiny bit bigger than the nav on mobile), but I think it's good to go.
