### ISSUE TITLE
Title font-size

### ISSUE THREAD

**Issue by TrentWalton** [raygunray/reaganray.com#9]
Related to #8, I bet a smaller font-size for phones would be good—specifically for headings / titles

<img width="340" alt="screen shot 2015-11-30 at 11 53 14 am" src="https://cloud.githubusercontent.com/assets/271248/11479710/0937d60c-9759-11e5-9dfb-0ddff23e4a96.png">

**Comment by raygunray** [comment]
I can wrestle that one a little bit more. Unfortunately, "thesignsofaustin.com" will always go off-screen since it's just a really long word (font-sizing probably won't fix it).

**Comment by raygunray** [comment]
Pushed a commit to this one. LMK what you think.
